spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: mainservice
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/admin/categories/**, /admin/compilations/**, /admin/comments/**, /admin/events/**, /admin/users/**, /categories/**, /compilations/**, /events/**, /users/**, /comments/**

        - id: stats-service
          uri: lb://STATS-SERVER
          predicates:
            - Path=/stats/**, /hit/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    loadbalancer:
      ribbon:
        enabled: false

resilience4j:
  circuitbreaker:
    instances:
      main service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50

server:
  port: 8080

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,gateway,metrics,prometheus
#      base-path: /actuator
#      cors:
#        allowed-origins: "*"
#        allowed-methods: GET,POST,PUT,DELETE
#  endpoint:
#    gateway:
#      enabled: true
#    health:
#      show-details: always
#      probes:
#        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  endpoint:
    gateway:
      enabled: true

info:
  app:
    name: ExploreWithMe Gateway
    description: API Gateway for ExploreWithMe application
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    reactor.netty.http.client: DEBUG