server:
  port: 0

# Основные настройки
spring:
  application:
    name: event-service
  config:
    activate:
      on-profile: default
  jpa:
    hibernate:
      ddl-auto: none
      connection: false
    transaction: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/main-db
    username: dbuser
    password: 12345
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss

# Настройки логирования
logging:
  level:
    ru.practicum.stats: INFO
    ru.practicum.client.EventClient: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org:
      hibernate.type.descriptor.sql.BasicBinder: Trace
      springframework.transaction.interceptor: TRACE

---
# Настройки для профиля test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:main-db
    username: dbuser
    password: 12345

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    collector:
      address: 'discovery:///collector'
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext